// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcG4tcUzSdKkxfkZxDpu6MsIlp-jxBbBg',
    appId: '1:495803754284:android:b8ee471a121479a1d56e89',
    messagingSenderId: '495803754284',
    projectId: 'flutterfirebasepractice-a3df0',
    databaseURL: 'https://flutterfirebasepractice-a3df0-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebasepractice-a3df0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlBY_UAcF0TTGXXNYycKadlxCfJNXc4cI',
    appId: '1:495803754284:ios:cb20d72959258c81d56e89',
    messagingSenderId: '495803754284',
    projectId: 'flutterfirebasepractice-a3df0',
    databaseURL: 'https://flutterfirebasepractice-a3df0-default-rtdb.firebaseio.com',
    storageBucket: 'flutterfirebasepractice-a3df0.appspot.com',
    androidClientId: '495803754284-8gtubn665n7738slh8iougtdkp6lph39.apps.googleusercontent.com',
    iosClientId: '495803754284-50m7op6495f8464o8dufm3bf26vfrlu1.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
